<?xml version="1.0" ?>
<!-- 
  UNIVERSIDAD NACIONAL DE COLOMBIA
  DEPARTAMENTO DE ING. MECANICA Y MECATRONICA
  ROBOTICA Y CONTROL SERVO VISUAL
  PROF: FLAVIO PRIETO
  
        SIMPLE DIFFERENTIAL ROBOT
  < - - - - ROBOT DESCRIPTION - - - - >

  AUTHOR: JURGEN H. KREJCI MUNOZ
  ROBOT: DIFFERTIAL DRIVE ROBOT
  MAIL: jhkrejcim@unal.edu.co
  VERSION: 1.0
  TESTED ON ROS NOETIC (UBUNTU 20.04.1 LTS)
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="differential">
      
<!-- Include -->
<xacro:include filename="$(find diff_driver_test)/urdf/robot_parameters.xacro" />
<xacro:include filename="$(find diff_driver_test)/urdf/my_diff_macros.xacro" />
<!-- END - Include -->


<!-- RViz Material Definition-->

<!-- Chasis -->
<material name="cyan">
  <color rgba="0.25 1.0 1.0 1.0"/>
</material>

<!-- Wheels -->
<material name="black">
  <color rgba="0.0 0.0 0.0 1.0"/>
</material>

<!-- Sphere -->
<material name="grey">
  <color rgba="0.47 0.47 0.47 1.0"/>
</material>
    
<!-- Gazebo Material Definition-->

<!-- Chasis -->
<gazebo reference="chasis">
  <material>Gazebo/BlueGlow</material>
</gazebo>

<!-- Wheels -->
<gazebo reference="left_wheel">
  <material>Gazebo/FlatBlack</material>
</gazebo>

<gazebo reference="right_wheel">
  <material>Gazebo/FlatBlack</material>
</gazebo>

<!-- Sphere -->
<gazebo reference="sphere_wheel">
  <material>Gazebo/Grey</material>
</gazebo>


<!-- * * * Robot Description * * * -->

<!-- Reference Frame -->
<link name="base_footprint"> 
</link>  

<!-- Footprint to chasis joint -->
<xacro:fixed_joint name="chasis_joint"
origin_xyz="0 0 ${ground_clearance+(base_height/2)}"
origin_rpy="0 0 0"
parent= "base_footprint"
child= "chasis"
/>

<!-- Chasis link -->
<xacro:rectangular_link name="chasis"
origin_xyz= "${(base_length/2)-wheel_radius} 0 0"
origin_rpy= "0 0 0"
length= "${base_length}"
width= "${base_width}"
height= "${base_height}"
material= "cyan"
/>

<!-- Chasis to left wheel joint -->
<xacro:wheel_joint name="left_wheel_joint"
child = "left_wheel"
parent = "chasis"
origin_xyz= "0 ${wheel_distance/2} 0"
origin_rpy= "${-1*pi/2} 0 0"
limit_e = "10"
limit_v = "10"
/>

<!-- Left wheel link -->
<xacro:wheel_link name="left_wheel"
radius= "${wheel_radius}"
width= "${(wheel_distance-base_width)}"
origin_xyz= "0 0 0"
origin_rpy= "0 0 0"
material = "black"
/>

<!-- Chasis to right wheel joint -->
<xacro:wheel_joint name="right_wheel_joint"
child = "right_wheel"
parent = "chasis"
origin_xyz= "0 ${-1*wheel_distance/2} 0"
origin_rpy= "${-1*pi/2} 0 0"
limit_e = "10"
limit_v = "10"
/>

<!-- Right wheel link -->
<xacro:wheel_link name="right_wheel"
radius= "${wheel_radius}"
width= "${(wheel_distance-base_width)}"
origin_xyz= "0 0 0"
origin_rpy= "0 0 0"
material = "black"
/>

<!-- Chasis to sphere wheel -->
<xacro:fixed_joint name="sphere_joint"
origin_xyz="${base_length-(2*wheel_radius)} 0 ${base_height/2}"
origin_rpy="0 0 0"
parent= "base_footprint"
child= "sphere_wheel"
/>

<!-- Sphere wheel link -->
<xacro:sphere_link name="sphere_wheel"
radius= "${ground_clearance}"
origin_xyz= "0 0 0"
origin_rpy= "0 0 0"
material = "grey"
/>

<!-- Transmissions -->

<!-- Left wheel transmission -->
<xacro:wheel_transmission name= "left_wheel_transmission"
joint= "left_wheel_joint"
/>

<!-- Left wheel transmission -->
<xacro:wheel_transmission name= "right_wheel_transmission"
joint= "right_wheel_joint"
/>

<!-- Gazebo Control plugin -->
<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
</gazebo> 

</robot>
