<?xml version="1.0" ?>
<!-- 
  UNIVERSIDAD NACIONAL DE COLOMBIA
  DEPARTAMENTO DE ING. MECANICA Y MECATRONICA
  ROBOTICA Y CONTROL SERVO VISUAL
  PROF: FLAVIO PRIETO
  
        SIMPLE DIFFERENTIAL ROBOT
  < - - - - ROBOT PARAMETERS - - - - >

  AUTHOR: JURGEN H. KREJCI MUNOZ
  ROBOT: DIFFERTIAL DRIVE ROBOT
  MAIL: jhkrejcim@unal.edu.co
  VERSION: 1.0
  TESTED ON ROS NOETIC (UBUNTU 20.04.1 LTS)
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="differential">
      
<xacro:property name="wheel_radius" value="0.1"/>
<xacro:property name="wheel_distance" value="0.36"/>
<xacro:property name="base_width" value="0.3"/>
<xacro:property name="base_length" value="0.5"/>
<xacro:property name="base_height" value="0.1"/>
<xacro:property name="ground_clearance" value="${wheel_radius-(base_height/2)}"/>

</robot>
